import type { Metadata } from 'next';
import Link from 'next/link';
import { SchemaOrg } from '@/components/SchemaOrg';

export const metadata: Metadata = {
  title: 'Kennisbank — waterfilters, osmose en waterkwaliteit',
  description:
    'Diepgaande artikelen over omgekeerde osmose, waterhardheid, kokend water kranen en waterkwaliteit in Nederland.',
  alternates: { canonical: 'https://waterfilterplatform.nl/kennisbank' },
  openGraph: {
    title: 'Kennisbank — waterfilters, osmose en waterkwaliteit',
    description: 'Diepgaande artikelen over omgekeerde osmose, waterhardheid, kokend water kranen en waterkwaliteit in Nederland.',
  },
};

const artikelen = [
  {
    slug: 'waterontharder-voordelen',
    titel: 'Waterontharder voordelen: wat levert het je op?',
    samenvatting: 'Overzicht van de voordelen van een waterontharder: minder kalk, zuinigere apparaten, zachte huid en lagere energiekosten.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-appartement',
    titel: 'Waterontharder in appartement: opties en beperkingen',
    samenvatting: 'Een waterontharder plaatsen in een appartement vraagt om compacte systemen; lees welke opties passen en wat de installatie-eisen zijn.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterhardheid-zeep',
    titel: 'Waterhardheid en zeep: waarom schuimt zeep minder bij hard water?',
    samenvatting: 'Hard water vermindert de schuimvorming van zeep en shampoo aanzienlijk; lees hoe kalk dit veroorzaakt en wat je eraan kunt doen.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-wijn',
    titel: 'Waterfilter voor wijn: beter water voor thuisvinificatie',
    samenvatting: 'Chloor en mineralen in kraanwater beïnvloeden de gist en smaak van zelfgemaakte wijn; leer welk waterfilter het beste resultaat geeft.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-tuin',
    titel: 'Waterfilter voor tuin: betere groei met gefilterd water',
    samenvatting: 'Gefilterd water verlaagt de kalkopbouw in de grond en kan de groei van planten en moestuin verbeteren; overzicht van geschikte systemen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-ondernemer',
    titel: 'Waterfilter voor ondernemers: welke systemen zijn zakelijk interessant?',
    samenvatting: 'Waterfiltersystemen voor zakelijk gebruik: welke typen zijn fiscaal aftrekbaar, onderhoudsarm en geschikt voor meerdere gebruikers?',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-kopen-tips',
    titel: 'Waterfilter kopen tips: voorkom veelgemaakte fouten',
    samenvatting: 'Praktische tips voor het kopen van een waterfilter: welke vragen je stelt, waar je op let en hoe je verborgen kosten vermijdt.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-koffie',
    titel: 'Waterfilter voor koffie: betere espresso en filterkoffie',
    samenvatting: 'Het juiste water is cruciaal voor koffiekwaliteit; lees welk waterfilter de ideale hardheid en TDS bereikt voor espresso en filterkoffie.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-garantie',
    titel: 'Waterfilter garantie: wat is gedekt en hoe lang?',
    samenvatting: 'Wat dekt de garantie op een waterfilter? Vergelijking van garantieperioden per merk en wat je moet weten bij een garantieclaim.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-gezond',
    titel: 'Is osmose water gezond? Feiten en fabels',
    samenvatting: 'Is osmosewater gezond of te puur om te drinken? We bespreken de wetenschappelijke stand van zaken over mineraalverlies en dagelijks gebruik.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-filter-vergelijken',
    titel: 'Osmose filter vergelijken: de beste systemen van 2026',
    samenvatting: 'Vergelijking van de populairste osmosefilters op prijs, filtercapaciteit, afvalwaterverhouding en installatiegemak.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'omgekeerde-osmose-huis',
    titel: 'Omgekeerde osmose voor thuis: complete gids',
    samenvatting: 'Alles wat je wilt weten over omgekeerde osmose voor thuisgebruik: hoe het werkt, kosten, installatie en de beste systemen.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'leidingwater-samenstelling',
    titel: 'Leidingwater samenstelling: wat zit er in jouw kraanwater?',
    samenvatting: 'Overzicht van de mineralen, stoffen en toevoegingen in Nederlands leidingwater en hoe de samenstelling per regio verschilt.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-koelkast',
    titel: 'Kraanwater via koelkast: filter, kwaliteit en onderhoud',
    samenvatting: 'Koelkasten met ingebouwd waterfilter leveren gekoeld kraanwater; leer hoe je het filter vervangt en wat het filtert.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-tegels-verwijderen',
    titel: 'Kalk van tegels verwijderen: methoden en producten',
    samenvatting: 'Witte kalkranden op badkamertegels verwijderen? Vergelijking van azijn, citroenzuur, commerciële ontkalkers en de beste aanpak per type tegel.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-douchedeur',
    titel: 'Kalk van douchedeur verwijderen: tips en producten',
    samenvatting: 'Witte kalkvlekken op de douchedeur effectief verwijderen en voorkomen: vergelijking van huismiddelen en commerciële producten.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'hardheid-water-berekenen',
    titel: 'Waterhardheid berekenen: van mmol/L naar °dH en ppm',
    samenvatting: 'Hoe reken je waterhardheid om tussen mmol/L, °dH, °fH en ppm? Stap-voor-stap uitleg met rekenvoorbeelden en een handig overzicht.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'bier-brouwen-water',
    titel: 'Water voor bier brouwen: mineralen, hardheid en filters',
    samenvatting: 'Het juiste water is essentieel voor thuisbierbrouwen; leer welke mineralen je nodig hebt per bierstijl en hoe je kraanwater aanpast.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-zout-verbruik',
    titel: 'Waterontharder zoutverbruik: hoeveel zout gebruik je per jaar?',
    samenvatting: 'Hoeveel zout verbruikt een waterontharder per jaar? Leer wat het verbruik bepaalt, wat het kost en hoe je het kunt verminderen.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterhardheid-baby',
    titel: 'Waterhardheid en baby\'s: is hard kraanwater veilig?',
    samenvatting: 'Is hard kraanwater veilig voor baby\'s? Lees wat de norm is voor flesvoeding, welke mineralen tellen en wanneer filteren nodig is.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-zwembad',
    titel: 'Waterfilter voor zwembad: chloor, algen en filtertypes',
    samenvatting: 'Welk waterfilter is geschikt voor een privézwembad of jacuzzi? Overzicht van zandfilters, cartridgefilters en aanvullende systemen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-test-thuis',
    titel: 'Waterfilter thuis testen: methoden en testpakketten',
    samenvatting: 'Hoe test je een waterfilter thuis op effectiviteit? Vergelijking van TDS-meting, teststrips en professionele waterlabanalyses.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-sportfles',
    titel: 'Waterfilter sportfles: zuiver water overal mee naartoe',
    samenvatting: 'Waterfilter sportfles voor onderweg: vergelijking van filtermethodes, merken en wanneer een filterfles slim is voor sport en reizen.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-huurappartement',
    titel: 'Waterfilter in huurappartement: opties zonder verbouwing',
    samenvatting: 'Waterfilter in huurappartement installeren zonder aanpassingen? Overzicht van filterkruiken, kraan-adapters en compacte osmosesystemen.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-huis-bouwen',
    titel: 'Waterfilter bij nieuwbouw: wat meteen inbouwen?',
    samenvatting: 'Bij het bouwen van een nieuw huis is het ideale moment om een waterfilter in te bouwplan: welke systemen zijn het meest geschikt?',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-haarkleur',
    titel: 'Waterfilter voor haarkleur: chloor en kalk verwijderen',
    samenvatting: 'Chloor en kalk in kraanwater tasten haarkleur aan. Lees welke douchefilters helpen en of een osmosesysteem het verschil maakt.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-eenpersoonshuishouden',
    titel: 'Waterfilter voor eenpersoonshuishouden: wat past het best?',
    samenvatting: 'Alleen wonen en een waterfilter kopen? Overzicht van compacte en betaalbare systemen die passen bij een laag waterverbruik.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-afval',
    titel: 'Waterfilter afval: hoe verwerk je gebruikte filterpatronen?',
    samenvatting: 'Wat doe je met oude filterpatronen? Lees welke merken inzamelprogramma\'s hebben, wat recyclebaar is en hoe je afval minimaliseert.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'vaatwasser-waterverzachter',
    titel: 'Vaatwasser waterverzachter: inbouw, zout en instelling',
    samenvatting: 'Elke vaatwasser heeft een ingebouwde waterverzachter. Leer hoe je het zout bijvult, de hardheid instelt en wanneer een extra ontharder loont.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'rvs-waterfilter',
    titel: 'RVS waterfilter: duurzaam alternatief voor plastic filters',
    samenvatting: 'Een RVS waterfilter gaat langer mee en bevat geen BPA. Vergelijking van types, schoonmaakinstructies en of ze even goed filteren.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-planten',
    titel: 'Osmose water voor planten: goed of te puur?',
    samenvatting: 'Is osmosewater goed voor planten of te puur? Lees welke planten er baat bij hebben en wanneer je mineralen moet toevoegen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-membraan-levensduur',
    titel: 'Osmose membraan levensduur: hoe lang gaat het mee?',
    samenvatting: 'Hoe lang gaat een osmose membraan mee? Lees welke factoren de levensduur bepalen, wanneer je het vervangt en wat vervanging kost.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-smaak',
    titel: 'Kraanwater smaak verbeteren: oorzaken en oplossingen',
    samenvatting: 'Kraanwater dat raar smaakt of ruikt? Lees wat chloor, kalk of leidingen hieraan bijdragen en welke filters de smaak verbeteren.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-koken',
    titel: 'Kraanwater koken: eetklaar en bacteriëvrij',
    samenvatting: 'Wanneer moet je kraanwater koken voordat je het gebruikt? Lees wanneer het nodig is, hoe lang en wat koken wel en niet verwijdert.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'keukenkraan-filter',
    titel: 'Keukenkraan filter: types, kosten en installatie',
    samenvatting: 'Welk keukenkraanfilter past bij jouw situatie? Vergelijking van kraanfilters, inline filters en complete osmosesystemen voor onder de gootsteen.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-verwarming',
    titel: 'Kalk in verwarming: schade, risico\'s en ontkalken',
    samenvatting: 'Kalk in vloerverwarming of radiatoren verlaagt de efficiëntie en kan leidingen beschadigen. Lees hoe je ontkalkt en het voorkomt.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'drinkwater-versus-flessenwater',
    titel: 'Drinkwater versus flessenwater: kwaliteit en kosten vergeleken',
    samenvatting: 'Is drinkwater uit de kraan beter dan flessenwater? Een directe vergelijking op mineralen, zuiverheid, prijs per liter en milieu-impact.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'best-kokend-water-kraan-test',
    titel: 'Best kokend water kraan test: onafhankelijke resultaten',
    samenvatting: 'Onafhankelijke testresultaten van de populairste kokend water kranen: temperatuur, filterkwaliteit, gebruiksgemak en kosten vergeleken.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'anti-kalk-tips',
    titel: 'Anti-kalk tips: voorkom kalkaanslag in huis',
    samenvatting: 'Praktische tips om kalkaanslag te voorkomen op kranen, douches en apparaten — zonder dure investeringen.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'chroom-drinkwater',
    titel: 'Chroom in drinkwater: risico\'s en oplossingen',
    samenvatting: 'Wat is chroom in drinkwater, hoe gevaarlijk is chroom-6 en welke filters verwijderen het effectief?',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'co2-patronen-vergelijken',
    titel: 'CO2-patronen vergelijken: welke past bij jouw systeem?',
    samenvatting: 'Vergelijking van CO2-patronen voor bruisend water thuis: maten, merken, kosten per liter en compatibiliteit.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'drinkwater-norm-nederland',
    titel: 'Drinkwaternorm Nederland: wat zijn de eisen?',
    samenvatting: 'Een overzicht van de wettelijke drinkwaternormen in Nederland en wat ze betekenen voor de kwaliteit van jouw kraanwater.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'drinkwater-normen-nederland',
    titel: 'Drinkwater normen Nederland: alle grenswaarden uitgelegd',
    samenvatting: 'Welke normen gelden er voor drinkwater in Nederland? Compleet overzicht van grenswaarden voor mineralen, metalen en stoffen.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'hardwatergebied-nederland',
    titel: 'Hardwatergebieden Nederland: waar is het water het hardst?',
    samenvatting: 'Kaart en overzicht van de hardwatergebieden in Nederland: welke regio\'s hebben de meeste kalk en wat kun je eraan doen?',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'ijzer-drinkwater',
    titel: 'IJzer in drinkwater: herkennen, meten en verwijderen',
    samenvatting: 'Roestkleurig water of ijzersmaak? Lees hoe ijzer in drinkwater ontstaat, wat de norm is en hoe je het effectief filtert.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-cv-ketel',
    titel: 'Kalk in CV-ketel: schade, ontkalken en voorkomen',
    samenvatting: 'Kalkaanslag in de CV-ketel verhoogt je energieverbruik en verkort de levensduur. Leer hoe je het voorkomt en ontkalkt.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-douche',
    titel: 'Kalk op douche en douchekop: verwijderen en voorkomen',
    samenvatting: 'Witte aanslag op de douchekop en douchewand? Ontdek de beste manieren om kalk te verwijderen en te voorkomen.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-ketel',
    titel: 'Kalk in waterkoker: ontkalken en schoonmaken',
    samenvatting: 'Aanslag in je waterkoker? Leer hoe je snel en effectief ontkalkt met azijn of citroenzuur en hoe je het voorkomt.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-vaatwasser',
    titel: 'Kalk in vaatwasser: voorkomen, zout en ontkalken',
    samenvatting: 'Kalk in de vaatwasser zorgt voor vlekken en slijtage. Ontdek hoe zout, ontkalkingsmiddel en een waterontharder helpen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-boiler',
    titel: 'Kokend water kraan met boiler: hoe werkt het?',
    samenvatting: 'Hoe verwarmt een kokend water kraan het water zo snel? Uitleg over de geïntegreerde boiler, capaciteit en energieverbruik.',
    categorie: 'Kokend Water',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-onderhoud',
    titel: 'Kokend water kraan onderhoud: filters en reiniging',
    samenvatting: 'Hoe onderhoud je een kokend water kraan? Overzicht van filtervervanging, ontkalken en serviceintervallen per merk.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-vergelijken',
    titel: 'Kokend water kraan vergelijken: alle merken en modellen',
    samenvatting: 'Uitgebreide vergelijking van kokend water kranen op prijs, capaciteit, filteropties en gebruiksgemak.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-veiligheid',
    titel: 'Kokend water kraan veiligheid: risico\'s en maatregelen',
    samenvatting: 'Is een kokend water kraan veilig thuis? Lees over kindersloten, brandwondrisico\'s en hoe merken veiligheid borgen.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-koelen',
    titel: 'Kraanwater koelen: de beste methoden en apparaten',
    samenvatting: 'Gekoeld kraanwater thuis zonder plastic flessen: vergelijking van waterkoelers, inline koelers en 4-in-1 kranen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-hardheid-meten',
    titel: 'Kraanwater hardheid meten: eenvoudige methoden thuis',
    samenvatting: 'Hoe meet je de hardheid van kraanwater thuis? Overzicht van teststrips, TDS-meter en druppeltest met uitleg van de waarden.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-vs-flessenwater',
    titel: 'Kraanwater vs flessenwater: kwaliteit, kosten en milieu',
    samenvatting: 'Is kraanwater beter dan flessenwater? Vergelijking op kwaliteit, smaak, kosten per liter en milieu-impact.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'mangaan-drinkwater',
    titel: 'Mangaan in drinkwater: norm, risico\'s en filters',
    samenvatting: 'Mangaan in drinkwater kan zwarte vlekken veroorzaken en is schadelijk bij hoge concentraties. Lees wat de norm is en hoe je het verwijdert.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'nitrieten-drinkwater',
    titel: 'Nitrieten in drinkwater: gevaar en oplossing',
    samenvatting: 'Nitrieten in drinkwater vormen een risico, met name voor zuigelingen. Leer het verschil met nitraat en hoe je ze effectief filtert.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'omgekeerde-osmose-nadelen',
    titel: 'Omgekeerde osmose nadelen: wat zijn de minpunten?',
    samenvatting: 'Wat zijn de echte nadelen van omgekeerde osmose? Van afvalwater tot mineraalverlies — eerlijk overzicht met nuance.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-filter-installatie',
    titel: 'Osmose filter installatie: stap-voor-stap handleiding',
    samenvatting: 'Zelf een osmosefilter installeren? Complete handleiding met benodigdheden, stappen en veelgemaakte fouten.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-filter-prijs',
    titel: 'Osmose filter prijs: wat kost een osmosesysteem?',
    samenvatting: 'Wat kost een osmosefilter? Overzicht van aanschafkosten, installatiekosten en jaarlijkse onderhoudskosten per type systeem.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-remineralisatie',
    titel: 'Osmose remineralisatie: mineralen toevoegen aan osmosewater',
    samenvatting: 'Osmosewater mist mineralen — remineralisatie lost dit op. Lees hoe remineralisatiefilters werken en welk type het beste is.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-vs-bronwater',
    titel: 'Osmose water vs bronwater: welke is gezonder?',
    samenvatting: 'Osmose water of bronwater — wat is zuiverder, wat zijn de kosten en welke mineralen zitten erin? Eerlijke vergelijking.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-koken',
    titel: 'Osmose water gebruiken voor koken: zinvol of niet?',
    samenvatting: 'Is osmosewater beter voor koken? We kijken naar smaak, kookgedrag en of het kwaad kan om mineraalarm water te gebruiken.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-zuur',
    titel: 'Is osmose water zuur? pH-waarde en gezondheid',
    samenvatting: 'Osmosewater heeft een lagere pH dan kraanwater. Is het zuur, wat zijn de gevolgen en wanneer moet je remineraliseren?',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'putwater-filter',
    titel: 'Putwater filteren: welk systeem heb je nodig?',
    samenvatting: 'Putwater bevat vaak bacteriën, ijzer of mangaan. Ontdek welke filters nodig zijn voor schoon en veilig drinkwater uit een put.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'water-besparen',
    titel: 'Water besparen thuis: tips voor minder verbruik',
    samenvatting: 'Praktische tips om thuis water te besparen in badkamer, keuken en tuin — inclusief welke apparaten het meeste verbruiken.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'water-zacht-maken',
    titel: 'Water zacht maken: methoden vergeleken',
    samenvatting: 'Hard water zacht maken kan op meerdere manieren. Vergelijking van waterontharder, osmose, ionenwisseling en kookwatermethode.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterbesparing-thuis',
    titel: 'Waterbesparing thuis: hoeveel kun je echt besparen?',
    samenvatting: 'Van korter douchen tot zuinige apparaten: ontdek hoeveel liter en euro je per jaar kunt besparen met slimme watergewoonten.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-aquarium',
    titel: 'Waterfilter voor aquarium: osmose of andere opties?',
    samenvatting: 'Welk waterfilter is geschikt voor een aquarium? Vergelijking van osmose, onthardingskolom en UV-filters voor zoet- en zeewater.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-baby',
    titel: 'Waterfilter voor baby: wat is veilig voor flesvoeding?',
    samenvatting: 'Welk water gebruik je voor flesvoeding? Lees of een osmosefilter of koolstoffilter het kraanwater veilig genoeg maakt voor baby\'s.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-douche',
    titel: 'Waterfilter voor douche: minder chloor en kalk',
    samenvatting: 'Een douchefilter vermindert chloor en kalk voor zachtere huid en haar. Vergelijking van types, merken en installatiegemak.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-gezondheid',
    titel: 'Waterfilter en gezondheid: wat filtert wat?',
    samenvatting: 'Welke gezondheidsvoordelen biedt een waterfilter? Overzicht van wat osmose, koolstof en UF-filters verwijderen en wat ze laten zitten.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-huurwoning',
    titel: 'Waterfilter in huurwoning: wat mag en wat werkt?',
    samenvatting: 'Waterfilter in een huurwoning installeren? Lees welke systemen geen toestemming vereisen en hoe je een osmosefilter plaatst zonder te boren.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-kantoor',
    titel: 'Waterfilter voor kantoor: de beste oplossingen',
    samenvatting: 'Schoon drinkwater op kantoor voor meerdere mensen: vergelijking van waterkoelers, osmosesystemen en filterkranen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-kopen-gids',
    titel: 'Waterfilter kopen: complete koopgids 2026',
    samenvatting: 'Alles wat je moet weten voordat je een waterfilter koopt: types, prijzen, filterwerking en de vragen die je moet stellen.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-milieu',
    titel: 'Waterfilter en milieu: beter dan flessenwater?',
    samenvatting: 'Is een waterfilter milieuvriendelijker dan flessenwater? Vergelijking van CO2-footprint, plastic afval en waterverbruik.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-prijs',
    titel: 'Waterfilter prijs: wat kost een waterfilter in 2026?',
    samenvatting: 'Overzicht van waterfilterkosten per type: van €20 filterkruik tot €800 osmosesysteem, inclusief jaarlijkse filterkosten.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-restaurant',
    titel: 'Waterfilter voor restaurant of horeca: wat heb je nodig?',
    samenvatting: 'Waterfilter voor de horeca: welke systemen zijn geschikt voor grote volumes, koffie, ijs en tapwater in restaurant of café?',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-rv',
    titel: 'Waterfilter voor RV: schoon water onderweg',
    samenvatting: 'Welk waterfilter is geschikt voor een RV of camper? Vergelijking van inline filters, osmosesystemen en filterkruiken op prijs en filterkwaliteit.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-soorten',
    titel: 'Waterfilter soorten: welk type past bij jou?',
    samenvatting: 'Overzicht van alle waterfiltertypen: filterkan, koolstoffilter, osmose, UF en waterontharder — met voor- en nadelen per type.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-werkzaamheid',
    titel: 'Waterfilter werkzaamheid: wat filtert een waterfilter echt?',
    samenvatting: 'Hoe effectief is een waterfilter? Overzicht van filterprestaties per type voor chloor, kalk, nitraat, PFAS en microplastics.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-installatie',
    titel: 'Waterontharder installatie: zelf doen of installateur?',
    samenvatting: 'Wat komt er kijken bij de installatie van een waterontharder? Overzicht van stappen, kosten en wanneer je een loodgieter nodig hebt.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-huren',
    titel: 'Waterontharder huren: kosten en wanneer het loont',
    samenvatting: 'Waterontharder huren of kopen? Vergelijk de maandelijkse kosten, servicecontracten en wanneer huur voordeliger is dan aanschaf.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-zout',
    titel: 'Waterontharder zout: soorten, verbruik en tips',
    samenvatting: 'Welk zout gebruik je in een waterontharder? Vergelijking van tablet-, blok- en kristalzout op prijs, kwaliteit en verbruik.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-zout-soorten',
    titel: 'Waterontharder zout soorten: welke is het beste?',
    samenvatting: 'Tabletzout, blokkenzout of kristalzout — wat is het verschil en welk zout geeft de beste prestaties in jouw waterontharder?',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterverzachter-alternatieven',
    titel: 'Waterverzachter alternatieven: wat werkt als vervanger?',
    samenvatting: 'Geen waterontharder willen maar toch minder kalk? Vergelijking van magnetische ontharders, polyfosfoaat, osmose en elektronische alternatieven.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-vergelijken-2026',
    titel: 'Waterfilter vergelijken 2026: welk systeem wint?',
    samenvatting: 'Nieuwe PFAS-normen en microplastics veranderden het speelveld in 2026. Ontdek welk filtersysteem past bij jouw woning en gezin.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'beste-kokend-water-kraan-2026',
    titel: 'Beste kokend water kraan 2026: top 5 vergeleken',
    samenvatting: 'Welke kokend water kraan is de beste keuze in 2026? Top 5 vergeleken op prijs, filteropties, installatie en kosten over 5 jaar.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: '4-in-1-kraan',
    titel: '4-in-1 kraan: kokend, koud, warm en bruisend water',
    samenvatting: 'Alles over de 4-in-1 kraan: hoe het werkt, welke merken het aanbieden, kosten en of het de investering waard is voor jouw keuken.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'arseen-drinkwater',
    titel: 'Arseen in drinkwater: gevaarlijk en wat kun je doen?',
    samenvatting: 'Arseen in drinkwater: wat is het, hoe gevaarlijk is het en hoe verwijder je het? Alles over de EU-norm, risico\'s en osmosefilters.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'drinkwater-baby',
    titel: 'Drinkwater voor baby\'s: kraanwater, fles of gefilterd?',
    samenvatting: 'Wanneer mag een baby water drinken? Kraanwater, flessenwater of osmosewater — lees wat veilig is voor zuigelingen.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'drinkwater-zwangerschap',
    titel: 'Drinkwater tijdens zwangerschap: wat is veilig?',
    samenvatting: 'Is kraanwater veilig tijdens de zwangerschap? We bespreken nitraat, lood, PFAS en chloor eerlijk en zonder overdrijving.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'fluor-drinkwater',
    titel: 'Fluor in drinkwater: toegevoegd of niet in Nederland?',
    samenvatting: 'Nederland voegt al decennia geen fluor toe aan drinkwater. Lees wat dat betekent en hoeveel fluoride er van nature in zit.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-koffiemachine',
    titel: 'Kalk in koffiemachine: ontkalken en voorkomen',
    samenvatting: 'Kalk in je koffiemachine verkort de levensduur en verslechtert de koffie. Leer hoe je ontkalkt, hoe vaak en hoe je aanslag voorkomt.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-wasmachine',
    titel: 'Kalk in wasmachine: schade, kosten en oplossing',
    samenvatting: 'Kalk in de wasmachine sloopt het verwarmingselement, verhoogt je energierekening en wast minder schoon. Ontdek de oplossingen.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalkvrij-koken',
    titel: 'Kalkvrij koken: tips en het beste water voor je pan',
    samenvatting: 'Kalkvrij koken en geen witte aanslag meer in je pan? Ontdek welk water het beste werkt en hoe je kalkranden eenvoudig verwijdert.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-baby',
    titel: 'Kokend water kraan met baby: veilig gebruik en tips',
    samenvatting: 'Kokend water kraan veilig met baby? Lees hoe het kinderslot werkt en of het water puur genoeg is voor flesvoeding.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'lood-drinkwater',
    titel: 'Lood in drinkwater: risico\'s, oorzaken en oplossing',
    samenvatting: 'Lood in kraanwater komt bijna altijd uit oude loodleidingen. Lees wat de risico\'s zijn en hoe een osmosefilter beschermt.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-membraan-types',
    titel: 'Osmose membraan types: TFC, CTA en welke het beste is',
    samenvatting: 'TFC of CTA membraan? Vergelijk zuiverheid, chloorbestendigheid, levensduur en kosten — en ontdek welk type het beste bij jouw situatie past.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-membraan-vervangen',
    titel: 'Osmose membraan vervangen: wanneer en hoe doe je dat?',
    samenvatting: 'Wanneer moet je het osmose membraan vervangen? Signalen herkennen, stap-voor-stap handleiding en de kosten van vervanging.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-aquarium',
    titel: 'Osmose water aquarium: wanneer en hoe gebruik je het?',
    samenvatting: 'Osmose water in je aquarium geeft volledige controle over GH, KH en TDS. Leer wanneer het zinvol is en hoe je remineraliseert.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-sport',
    titel: 'Osmose water en sport: is het goed voor sporters?',
    samenvatting: 'Is osmosewater goed voor sporters? We kijken naar elektrolyten, hydratie en wanneer aanvulling nodig is. Eerlijk advies.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'ph-waarde-drinkwater',
    titel: 'pH-waarde drinkwater: wat is ideaal voor je gezondheid?',
    samenvatting: 'Wat is de ideale pH-waarde voor drinkwater? Van WHO-normen tot alkalisch water claims — een eerlijk wetenschappelijk overzicht.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'regenwater-drinken',
    titel: 'Regenwater drinken: kan het en wat is er nodig?',
    samenvatting: 'Is regenwater drinken veilig? Wat zit erin, waarvoor is het geschikt en welke filterstappen zijn nodig om het drinkbaar te maken?',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'tds-meter-kopen',
    titel: 'TDS-meter kopen: hoe gebruik je het en wat meet je?',
    samenvatting: 'TDS-meter kopen voor drinkwater? Leer wat een TDS-meter meet, hoe je het gebruikt en wat normale waarden zijn voor osmosewater.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'tds-water',
    titel: 'TDS-waarde water: wat is het en wat is normaal?',
    samenvatting: 'Wat is TDS in drinkwater? De mg/L schaal, WHO-normen, het verschil met osmosewater en wanneer een lage TDS beter of slechter is.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'water-koffie',
    titel: 'Water voor koffie: ideale hardheid en TDS voor espresso',
    samenvatting: 'Welk water geeft de beste koffiesmaak? Leer over TDS, waterhardheid, mineralen en osmose water voor espresso en filterkoffie.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'water-thee',
    titel: 'Water voor thee: welke temperatuur en hardheid?',
    samenvatting: 'Welk water is het beste voor thee? Leer over watertemperatuur per theesoort, waterhardheid en hoe kalk uw theesmaak bederft.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-camper',
    titel: 'Waterfilter voor camper of caravan: welk type?',
    samenvatting: 'Welk waterfilter is geschikt voor camper of caravan? Vergelijking van inline koolstof, UF, RO en filterkruiken op prijs en filterkwaliteit.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-huren',
    titel: 'Waterfilter huren of kopen: wat is voordeliger?',
    samenvatting: 'Waterfilter huren of kopen? Vergelijk kosten op 3 en 5 jaar en ontdek wanneer huur slim is en wanneer kopen veel voordeliger uitpakt.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-installatie-kosten',
    titel: 'Waterfilter installeren: kosten en wat je nodig hebt',
    samenvatting: 'Waterfilter installeren: wat kost het per type filter, wanneer doe je het zelf en wanneer heb je een installateur nodig?',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-onderhoud',
    titel: 'Waterfilter onderhoud: hoe en hoe vaak?',
    samenvatting: 'Waterfilter onderhoud per filtertype: filterkan, koolstoffilter, osmose systeem en meer. Inclusief kosten per jaar en onderhoudschema\'s.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-test',
    titel: 'Waterfilter test: hoe test je of je filter werkt?',
    samenvatting: 'Waterfilter testen? Ontdek 4 methodes: TDS-meter, smaaktest, teststrips en professioneel wateronderzoek. Weet wanneer je filter versleten is.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterhardheid-meten',
    titel: 'Waterhardheid meten: methoden, strips en TDS-meter',
    samenvatting: 'Waterhardheid meten? Vergelijk teststrips, TDS-meter, druppeltest en labonderzoek. Met uitleg over °dH, °fH en ppm.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'zacht-water-voordelen',
    titel: 'Zachte water voordelen: minder kalk, zuiniger en meer',
    samenvatting: 'Zacht water voordelen én nadelen eerlijk uitgelegd. Minder kalk, minder wasmiddel, langere apparaatlevensduur — en wanneer het te zacht wordt.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterkwaliteit-nederland',
    titel: 'Waterkwaliteit Nederland: hoe schoon is ons kraanwater echt?',
    samenvatting: 'Hoe schoon is Nederlands kraanwater? Lees over normen, controle, regionale verschillen en wanneer filteren zinvol is.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'pfas-waterfilter',
    titel: 'PFAS waterfilter: welke filters verwijderen PFAS?',
    samenvatting: 'Welk waterfilter verwijdert PFAS uit drinkwater? Vergelijking van osmose, actieve kool en andere systemen op effectiviteit.',
    categorie: 'Waterfilter',
    datum: '13 mei 2026',
  },
  {
    slug: 'pfas-drinkwater',
    titel: 'PFAS in drinkwater: hoe erg is het & wat helpt?',
    samenvatting: 'PFAS in drinkwater — wat zijn forever chemicals, hoe erg is het in Nederland en welke filters helpen écht? Eerlijk overzicht.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'microplastics-drinkwater',
    titel: 'Microplastics in drinkwater: hoe erg & wat helpt?',
    samenvatting: 'Microplastics in kraanwater — wat weten we, wat is het risico en welke filters verwijderen ze? Nuchter overzicht met de feiten.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'chloor-in-drinkwater',
    titel: 'Chloor in drinkwater: nuttig of schadelijk?',
    samenvatting: 'Zit er chloor in Nederlands kraanwater? Hoeveel, hoe schadelijk, en hoe verwijder je het? Met praktische tips en filtervergelijking.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'filterkan-vs-osmose',
    titel: 'Filterkan vs osmose filter: welke kies je?',
    samenvatting: 'Filterkan of osmose? Vergelijk beide systemen op zuiverheid, kosten per liter en gemak — en ontdek welk filter het beste bij jou past.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'brita-vs-osmose',
    titel: 'Brita vs osmose filter: eerlijke vergelijking',
    samenvatting: 'Brita of osmose filter — wat filtert beter en wat is goedkoper? Eerlijke vergelijking op filterwerking, kosten en toepassingen.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-keuken',
    titel: 'Waterfilter keuken: welk systeem past bij jou?',
    samenvatting: 'Welk waterfilter past in jouw keuken? Vergelijk filterkan, inline filter, osmose en 4-in-1 kraan op prijs, werking en installatiegemak.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-verwijderen-water',
    titel: 'Kalk verwijderen uit water: alle methoden vergeleken',
    samenvatting: 'Kalk verwijderen uit leidingwater? Vergelijk waterontharder, osmose filter en magnetische ontharder op werking, kosten en effectiviteit.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-onder-aanrecht',
    titel: 'Waterfilter onder aanrecht: types, kosten & installatie',
    samenvatting: 'Een waterfilter onder het aanrecht installeren? Vergelijk koolstoffilter, osmose en 4-in-1 systemen op prijs, ruimtegebruik en filterkwaliteit.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'reverse-osmosis-nadelen',
    titel: 'Omgekeerde osmose nadelen: eerlijk overzicht',
    samenvatting: 'Wat zijn de nadelen van omgekeerde osmose? Afvalwater, mineralen, kosten en snelheid eerlijk besproken — en hoe moderne systemen deze oplossen.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-kopen',
    titel: 'Osmose water kopen: systeem of flessenwater?',
    samenvatting: 'Osmose water kopen in flessen of zelf thuis maken? Vergelijk kosten, kwaliteit en gemak — en ontdek waarom een eigen systeem al snel goedkoper is.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'bruisend-water-thuis',
    titel: 'Bruisend water thuis: de beste opties vergeleken',
    samenvatting: 'SodaStream, onderaanrecht-systeem of 4-in-1 kraan? We vergelijken alle opties voor bruisend water thuis op prijs, kwaliteit en kosten over 3 jaar.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water',
    titel: 'Osmose water: wat is het en hoe maak je het thuis?',
    samenvatting: 'Wat is osmose water, hoe zuiver is het en hoe maak je het thuis? Vergelijking met flessenwater, kosten per liter en de beste systemen.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-in-huis',
    titel: 'Kalk in huis: oorzaken, gevolgen en de beste oplossing',
    samenvatting: 'Witte aanslag, verstopte apparaten, hogere energierekening — kalk kost je meer dan je denkt. Ontdek de oorzaken en de beste structurele oplossing.',
    categorie: 'Waterkwaliteit',
    datum: '1 april 2026',
  },
  {
    slug: 'waterfilter-vergelijken',
    titel: 'Waterfilter vergelijken: welk systeem past bij jou?',
    samenvatting: 'Filterkan, osmosefilter, waterontharder of 4-in-1 kraan? We vergelijken alle types eerlijk op prijs, werking en toepassingen.',
    categorie: 'Vergelijken',
    datum: '1 maart 2026',
  },
  {
    slug: 'kokend-water-kraan-installeren',
    titel: 'Kokend water kraan installeren: stap-voor-stap handleiding',
    samenvatting: 'Zelf een kokend water kraan installeren? Volg deze complete handleiding voor een veilige en correcte installatie, inclusief tips en veelgemaakte fouten.',
    categorie: 'Installatie',
    datum: '15 maart 2026',
  },
  {
    slug: 'waterhardheid-verlagen',
    titel: 'Waterhardheid verlagen: oorzaken, gevolgen en oplossingen',
    samenvatting: 'Hard water veroorzaakt kalk in huis. Leer hoe je waterhardheid verlaagt met de juiste waterfilter, waterontharder of osmosesysteem.',
    categorie: 'Waterhardheid',
    datum: '15 februari 2026',
  },
  {
    slug: 'osmose-water-apparaat',
    titel: 'Osmose water apparaat kopen: kosten, types en tips',
    samenvatting: 'Welk osmose water apparaat past bij jou? Vergelijk de types op prijs, capaciteit en functies — van €150 losse filter tot complete 4-in-1 kraan.',
    categorie: 'Osmose',
    datum: '1 februari 2026',
  },
  {
    slug: 'osmose-water-drinken',
    titel: 'Osmose water drinken — is het gezond?',
    samenvatting: 'Is osmose water drinken gezond? We bespreken de effecten, de mineralen die ontbreken, en wanneer een remineralisatiefilter zinvol is.',
    categorie: 'Osmose',
    datum: '15 januari 2026',
  },
  {
    slug: 'nitraat-drinkwater',
    titel: 'Nitraat in drinkwater: risico\'s, normen en de beste oplossing',
    samenvatting: 'Is nitraat in drinkwater gevaarlijk? Lees over normen, wie risico loopt (zuigelingen!) en hoe een osmosefilter 95% van het nitraat verwijdert.',
    categorie: 'Waterkwaliteit',
    datum: '20 april 2026',
  },
  {
    slug: 'waterontharder-kosten',
    titel: 'Waterontharder kosten: aanschaf, installatie en zout',
    samenvatting: 'Wat kost een waterontharder echt? Compleet overzicht van aanschaf (€500–2000), installatie, zoutverbruik, onderhoud en terugverdientijd.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder',
    titel: 'Waterontharder: hoe werkt het en wanneer is het slim?',
    samenvatting: 'Waterontharder kopen of toch een osmosefilter? We vergelijken beide systemen eerlijk op prijs, werking en toepassingen voor thuis.',
    categorie: 'Waterhardheid',
    datum: '15 april 2026',
  },
  {
    slug: 'kalk-verwijderen-apparaten',
    titel: 'Kalk verwijderen uit huishoudelijke apparaten',
    samenvatting: 'Kalk verwijderen uit waterkoker, koffiemachine, strijkijzer en stoomreiniger: per apparaat de beste methode en preventie.',
    categorie: 'Kalk',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-zwangerschap',
    titel: 'Kraanwater tijdens zwangerschap: veilig en praktisch advies',
    samenvatting: 'Is kraanwater veilig tijdens de zwangerschap? Lood, PFAS en chloor uitgelegd voor zwangere vrouwen. RIVM-advies per trimester.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'ontkalker-vs-waterontharder',
    titel: 'Ontkalker vs waterontharder: wat is het verschil?',
    samenvatting: 'Ontkalker of waterontharder? Het echte verschil, welke problemen elk type oplost en wanneer welk systeem de juiste keuze is.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'putwater-behandelen',
    titel: 'Putwater behandelen en filteren: complete gids',
    samenvatting: 'Alles over verontreinigingen in putwater: bacteriën, nitraten, ijzer en hardheid. Filteropties en wanneer osmose noodzakelijk is.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'tds-water-uitleg',
    titel: 'TDS water uitleg voor beginners: alles over ppm',
    samenvatting: 'Wat is TDS in water? Uitleg over Total Dissolved Solids, ppm vs mg/L, osmose versus kraanwater en de ideale TDS per toepassing.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'water-mineralen-gezondheid',
    titel: 'Mineralen in water en gezondheid: wat draagt drinkwater bij?',
    samenvatting: 'Calcium, magnesium, natrium, fluoride in drinkwater. Wat draagt water bij aan je mineraalbehoefte en wanneer is mineraalarm water een zorg?',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-energie',
    titel: 'Energieverbruik waterfilters: wat kost het echt per jaar?',
    samenvatting: 'Vergelijk energieverbruik van osmosepompen, UV-lampen en kokendwaterkraan boilers. Bereken jaarkosten en bespaar door ontkalking.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-huis-renovatie',
    titel: 'Waterfilter bij huisrenovatie: planning en kosten',
    samenvatting: 'Waterfilter inbouwen tijdens renovatie? Het juiste moment, leidingwerk voor osmose, electra voor kokend water kraan en verborgen kosten.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-installatie',
    titel: 'Waterfilter installeren: stap-voor-stap gids',
    samenvatting: 'Waterfilter zelf installeren? Van filterkan tot osmose onder aanrecht: gereedschap, verbindingstypes en wanneer je een loodgieter nodig hebt.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-kelder',
    titel: 'Waterfilter in de kelder installeren: voor- en nadelen',
    samenvatting: 'Waterfilter in de kelder: optimale temperatuur, vochtproblemen, loodvrij leidingwerk en centrale installatievoordelen uitgelegd.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-kosten-overzicht',
    titel: 'Waterfilter kosten: compleet overzicht per systeemtype',
    samenvatting: 'Wat kost een waterfilter echt? Aanschaf, installatie, filters, energie en reparatie per systeemtype vergeleken over 10 jaar.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-nieuwbouw',
    titel: 'Waterfilter in nieuwbouwhuis: het juiste moment en systeem',
    samenvatting: 'Waterfilter in nieuwbouw plannen? Wanneer installeren, waterhardheid per locatie en welk systeem het beste past bij nieuwbouw.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-onder-keuken',
    titel: 'Waterfilter onder keuken aanrecht installeren',
    samenvatting: 'Ruimte-efficiënte oplossingen voor waterfilter onder aanrecht: filtratiestappen, aparte tapkraan en veelgemaakte fouten.',
    categorie: 'Installatie',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-subsidie',
    titel: 'Waterfilter subsidie Nederland: dit zijn de mogelijkheden',
    samenvatting: 'Subsidies voor waterfilters in Nederland? Overzicht van ISDE, SEEH, KIA, gemeentelijke regelingen en wat wel en niet in aanmerking komt.',
    categorie: 'Praktisch',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-hoe-lang',
    titel: 'Hoe lang gaat een waterontharder mee? Levensduur uitgelegd',
    samenvatting: 'Een waterontharder gaat 10–25 jaar mee. Factoren die de levensduur bepalen en hoe je repareren vs. vervangen afweegt.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-merken',
    titel: 'Waterontharder merken vergelijken: eerlijk overzicht',
    samenvatting: 'Kinetico, BWT, Harvey, Hague, Clack vergeleken zonder reclame. Kenmerken, garanties, Nederlandse service en wanneer goedkoper volstaat.',
    categorie: 'Vergelijken',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterontharder-onderhoud',
    titel: 'Waterontharder onderhoud: complete gids voor 2026',
    samenvatting: 'Waterontharder onderhoud: harsbed reinigen, zoutbrug voorkomen, regeneratiecyclus controleren en wanneer professioneel onderhoud nodig is.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'zacht-water-nadelen',
    titel: 'Nadelen van zacht water: wanneer is zacht te zacht?',
    samenvatting: 'Zacht water heeft ook nadelen: corrosief voor leidingen, laag TDS, risico op lood en koper. Wanneer zacht water problemen veroorzaakt.',
    categorie: 'Waterhardheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-kosten',
    titel: 'Kokend water kraan kosten: aanschaf tot energieverbruik',
    samenvatting: 'Complete kostenoverzicht kokend water kraan: aanschaf €200–1000+, installatie, filterkosten, energie en 10-jaars totaalkosten vergeleken.',
    categorie: 'Kokend water kraan',
    datum: '13 mei 2026',
  },
  {
    slug: 'kalk-leidingen-schade',
    titel: 'Kalkschade aan leidingen: kosten en preventie',
    samenvatting: 'Hoe kalk zich afzet in PVC, koper en RVS leidingen, impact op warmtewisselaars en wat leidingvervanging vs waterontharder kost.',
    categorie: 'Kalk',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-nadelen',
    titel: 'Nadelen van een kokend water kraan: eerlijk overzicht',
    samenvatting: 'Kokend water kraan nadelen: veiligheidsrisico\'s, energieverbruik, installatievereisten en kosten vergeleken met een waterkoker.',
    categorie: 'Kokend water kraan',
    datum: '13 mei 2026',
  },
  {
    slug: 'kokend-water-kraan-reinigen',
    titel: 'Kokend water kraan reinigen en onderhoud',
    samenvatting: 'Kalkaanslag van de tuit verwijderen, interne ontkalking, filter en membraan vervangen. Onderhoudsfrequentie per waterhardheidzone.',
    categorie: 'Kokend water kraan',
    datum: '13 mei 2026',
  },
  {
    slug: 'kraanwater-buitenland',
    titel: 'Kraanwater in het buitenland: wanneer veilig?',
    samenvatting: 'Welke landen hebben veilig kraanwater? Wanneer heb je zuivering nodig? Draagbare waterfilters voor reizigers per continent.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'leidingwater-samenstelling-2026',
    titel: 'Leidingwater samenstelling Nederland 2026: per regio',
    samenvatting: 'Ca, Mg, Na, sulfaat en NO3 per waterbedrijf: PWN, Dunea, WML, WMD, Vitens en meer. Hoe je jouw lokale data opzoekt.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'nitriet-drinkwater',
    titel: 'Nitriet in drinkwater: risico\'s, normen en osmosefilter',
    samenvatting: 'Nitriet vs nitraat (NO2 vs NO3), bacteriële omzetting, methemoglobinemia bij zuigelingen, EU-norm 0,1 mg/L en wanneer osmose nodig.',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-filter-capaciteit',
    titel: 'Osmosefilter capaciteit kiezen: 50, 75 of 150 GPD?',
    samenvatting: 'Wat betekent GPD bij een osmosefilter? Hoeveel liter per dag heb je nodig? Vergelijk 50, 75 en 150 GPD met invloed van druk en temperatuur.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-koken-recepten',
    titel: 'Osmosewater in de keuken: koken, bakken en recepten',
    samenvatting: 'Wat doet osmosewater met pasta, rijst en soep? Smaaktests, minder zout bij bakken en wanneer mineraalwater in recepten beter is.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'osmose-water-nier',
    titel: 'Osmosewater en nierwerking: advies bij nierziekten',
    samenvatting: 'Osmosewater en nierziekten: advies voor dialysepatiënten, wat nefrologen zeggen over remineralisatie en wanneer voorzichtigheid geboden is.',
    categorie: 'Osmose',
    datum: '13 mei 2026',
  },
  {
    slug: 'water-koken-gezond',
    titel: 'Water koken en gezondheid: wat verdwijnt, wat blijft?',
    samenvatting: 'Wat doet koken met bacteriën, virussen, chloor, nitraten en zware metalen? Wanneer is koken genoeg en wanneer heb je een waterfilter nodig?',
    categorie: 'Waterkwaliteit',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-aquarium-garnalenwater',
    titel: 'Waterfilter voor garnalen in aquarium: TDS en GH instellen',
    samenvatting: 'Osmosewater voor neocaridina en caridina garnalen: TDS-eisen, GH/KH instellen, remineralisatie met Salty Shrimp en de juiste RO-installatie.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-boot',
    titel: 'Waterfilter voor boot en jacht: complete gids',
    samenvatting: '12V RO-systemen, UV-filters, tankwater zuiveren en stroomverbruik op accu. Alles voor veilig drinkwater op boot of jacht.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-caravan',
    titel: 'Waterfilter voor caravan op vaste standplaats',
    samenvatting: 'Leidingwater vs tankwater, bacteriegroei bij stilstand, inline sediment+koolstof combinatie en UV voor tankwater in de caravan.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-diabetes',
    titel: 'Waterfilter bij diabetes: arseen, PFAS en osmosewater',
    samenvatting: 'Arseen en PFAS verhogen het risico op diabetes type 2. Wat zegt onderzoek? Helpt een osmosefilter bij diabetes? Praktisch advies.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-espresso',
    titel: 'Het perfecte water voor espresso en koffie',
    samenvatting: 'SCA-normen voor espressowater (75-150 mg/L TDS, pH 6-8), GH en KH, osmose met remineralisatie voor barista-water en anti-kalk tips.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-glazenwasserij',
    titel: 'Waterfilter voor ramen wassen: vlekvrij met 0 TDS',
    samenvatting: 'Demineralisatie voor vlekvrij ramen wassen, TDS-meter aflezen, RO vs DI systemen voor professionele glazenwassers en DIY ROI-berekening.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-hond-kat',
    titel: 'Waterfilter voor hond en kat: wanneer het zinvol is',
    samenvatting: 'Fluoride bij katten met nierziekte, nitraat bij honden, petfountain filters en wanneer een dierenarts een waterfilter aanbeveelt.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-huidverzorging',
    titel: 'Waterfilter voor huidverzorging: hard water en eczeem',
    samenvatting: 'Hard water irriteert huid bij eczeem en psoriasis. King\'s College onderzoek toont het verband. Welk waterfilter helpt echt?',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-kookplaat-inductie',
    titel: 'Waterfilter en kookplaat: kalk in pannen bij inductie',
    samenvatting: 'Hoe hard water kalkaanslag in steelpannen bij inductie veroorzaakt, kalkvrij koken beschermt pannen en hoe gefilterd water kooktijden beïnvloedt.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-legionella',
    titel: 'Legionella in leidingwater thuis: risico\'s en waterfilters',
    samenvatting: 'Legionella groeit bij 25–50°C. Wanneer helpt een waterfilter, wanneer niet, en welke UV-filter het risico elimineert.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-senioren',
    titel: 'Waterfilter voor ouderen: eenvoudig en veilig',
    samenvatting: 'Senioren zijn extra kwetsbaar voor waterverontreinigingen. Welke waterfilters passen het beste bij 65+: eenvoudig in gebruik en onderhoud.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-sportschool',
    titel: 'Waterfilter voor sportscholen en fitnesscentra',
    samenvatting: 'Waterfilters voor sportscholen: dagverbruik berekenen, RO-systemen, HORECA-normen, hygiëne-eisen en kosten per lid.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterfilter-tandenborstel',
    titel: 'Waterfilter voor tandenpoetsen: fluoride en tanden',
    samenvatting: 'Is osmosewater goed voor tandenpoetsen? Wat tandartsen zeggen over fluoride, kinderen en dagelijks poetsen met gefilterd water.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterhardheid-planten',
    titel: 'Waterhardheid en planten: welk water voor tuin',
    samenvatting: 'Welke waterhardheid willen moestuinplanten, azalea\'s en bloembollen? Regenwater vs leidingwater vs osmose voor tuin en moestuin.',
    categorie: 'Toepassingen',
    datum: '13 mei 2026',
  },
  {
    slug: 'waterstofwater-gezondheid',
    titel: 'Waterstofwater: claims, bewijs en osmosewater vergelijking',
    samenvatting: 'Waterstofwater belooft veel, maar wat zegt wetenschappelijk onderzoek echt? Evidence-based vergelijking met osmosewater en kostenoverzicht.',
    categorie: 'Gezondheid',
    datum: '13 mei 2026',
  },
];

export default function KennisbankPage() {
  return (
    <>
      <SchemaOrg
        type="BreadcrumbList"
        breadcrumbs={[
          { name: 'Home', url: 'https://waterfilterplatform.nl' },
          { name: 'Kennisbank', url: 'https://waterfilterplatform.nl/kennisbank' },
        ]}
      />

      <section className="bg-gradient-to-b from-[#E0F2FE] to-white py-10 px-4">
        <div className="max-w-3xl mx-auto">
          <nav className="text-xs text-gray-400 mb-4">
            <Link href="/" className="hover:text-[#005F8A]">Home</Link>
            <span className="mx-2">/</span>
            <span>Kennisbank</span>
          </nav>
          <h1 className="text-3xl md:text-4xl font-bold text-[#003F5C] mb-4">Kennisbank</h1>
          <p className="text-gray-600 text-lg">
            Diepgaande artikelen over waterfilters, waterkwaliteit en alles wat je wilt weten over osmose water en kokend water kranen.
          </p>
        </div>
      </section>

      <div className="max-w-3xl mx-auto px-4 py-10">
        <div className="space-y-4">
          {artikelen.map(a => (
            <Link
              key={a.slug}
              href={`/kennisbank/${a.slug}`}
              className="group block border border-gray-100 rounded-2xl p-5 hover:border-[#005F8A] hover:shadow-sm transition-all"
            >
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs bg-[#E0F2FE] text-[#005F8A] px-2 py-0.5 rounded-full font-medium">{a.categorie}</span>
                <span className="text-xs text-gray-400">{a.datum}</span>
              </div>
              <h2 className="font-bold text-gray-900 group-hover:text-[#005F8A] transition-colors mb-1">{a.titel}</h2>
              <p className="text-sm text-gray-500">{a.samenvatting}</p>
            </Link>
          ))}
        </div>
      </div>
    </>
  );
}
