import type { MetadataRoute } from 'next';
import { gemeenten } from '@/data/gemeenten';
import fs from 'fs';
import path from 'path';
import {
  routeLastModified,
  gitCommitDate,
  mdxFrontmatterDate,
  pickLastModified,
} from '@/lib/sitemap-dates.mjs';

const BASE = 'https://waterfilterplatform.nl';

// Computed once per build; used as the fallback when no git/frontmatter date exists.
const BUILD_DATE = new Date();

function getKennisbankSlugs(): string[] {
  const dir = path.join(process.cwd(), 'content/kennisbank');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.mdx'))
    .map(f => f.replace('.mdx', ''));
}

/** Realistic lastModified for a gemeente sub-route via its [gemeente] template. */
function gemeenteTemplateDate(segment: string): Date {
  return pickLastModified({
    gitDate: gitCommitDate(`app/${segment}/[gemeente]/page.tsx`),
    buildDate: BUILD_DATE,
  });
}

export default function sitemap(): MetadataRoute.Sitemap {
  const staticPages: MetadataRoute.Sitemap = [
    { url: BASE, lastModified: new Date(), changeFrequency: 'weekly', priority: 1.0 },
    { url: `${BASE}/omgekeerde-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/omgekeerde-osmose/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/omgekeerde-osmose/wat-is-osmose-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/voor-thuis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kokend-water-kraan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/kokend-water-kraan/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/kokend-water-kraan/met-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/heet-water-kraan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-filter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-filter/werking`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/filter`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${BASE}/waterhardheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kennisbank`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${BASE}/over-ons`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: `${BASE}/methodologie`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.6 },
    { url: `${BASE}/contact`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: `${BASE}/quooker-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/grohe-red-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/sodastream-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/beste-waterfilter-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-osmosefilter-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/the-source`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/purefilter-review`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/brita-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zerowater-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/aquatru-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/selsiuz`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/selsiuz-prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/selsiuz-onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/grohe-blue`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/grohe-blue-prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/grohe-blue-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/quooker-vs-grohe-red`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/selsiuz-vs-grohe-blue`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/sodastream`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/sodastream-co2`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/sodastream-prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/insinkerator`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/waterdrop`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/sodastream-vs-grohe-blue`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/waterdrop-vs-aquatru`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/grohe-red`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/grohe-red-prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/grohe-red-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/grohe-red-vs-grohe-blue`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/bwt-vs-brita`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/brita-vs-zerowater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/boretti-vs-quooker`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/quooker-vs-fonteq`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/waterontharder-vs-magneet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/gedestilleerd-vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/actief-kool-vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/filterkan-vs-kraanfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/onderbouw-vs-opzet-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/uv-vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/ionenwisselaar-vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/bronwater-vs-mineraalwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/kokend-kraan-vs-waterkoker`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/zoutloos-vs-ionenwisselaar`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/vier-in-een-vs-apart`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/keramisch-vs-koolstof`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/beste-kokend-water-kraan-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/4-in-1-kraan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaterkwaliteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/insinkerator-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/selsiuz-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/grohe-blue-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/boretti-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/beste-waterontharder-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/begrippenlijst`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/onderwerpen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${BASE}/water-in-de-keuken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/water-en-gezondheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/kalk-en-apparaten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/begrippen-en-technieken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/fonteq-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/waterdrop-alternatief`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/beste-filterkan-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/vergelijken/quooker-vs-selsiuz`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/grohe-blue-vs-grohe-red`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/bwt-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/grunbeck-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/ecowater-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/harvey-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/viteau-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${BASE}/aquacell-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${BASE}/maxima-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${BASE}/culligan-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/kinetico-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/erie-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/joep-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/nadelen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/gezondheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/vergelijken/bwt-vs-grunbeck`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/harvey-vs-bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/vergelijken/zoutloze-waterontharder-vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/drinkwaterfontein/soorten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/drinkwaterfontein/leidinggebonden-vs-fles`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/drinkwaterfontein/met-bruiswater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/drinkwaterfontein/koeling`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${BASE}/drinkwaterfontein/contactloos`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${BASE}/waterfilter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/soorten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/prijs`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: `${BASE}/waterontharder/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/installeren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/boiler`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/5-in-1`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterhardheid/kaart`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterhardheid/verlagen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/prijs`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: `${BASE}/waterfilter/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: `${BASE}/leidingwater`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${BASE}/drinkwater/kwaliteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/ph`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/remineralisatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/gezondheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/voor-hard-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/zout`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/energie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-filter/prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/smaak`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/onderhoud-schema`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterhardheid/testen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/abonnement`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/zonder-afvalwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/keuken-installatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterhardheid/regio`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/membraan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/onder-aanrecht`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/voor-aquarium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/4-in-1`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/waterontharder/elektrisch`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/camper`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/huren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/zwangerschap`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/gezond`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/douche`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/aquarium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/appartement`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/baby`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/koken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/baby`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kokend-water-kraan/prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/sport`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/koffiezetter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/koelkast`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/wasmachine`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/tuin`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/waterfilter/welk-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/osmose-vs-koolstof`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterhardheid/meten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-filter/installatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/kwaliteit-test`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/smaak-verbetering`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/fluoride`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-filter/capaciteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/microplastics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/pfas`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/drinkwater/lood`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/kokend-water-kraan/duurzaamheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/chloor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/afvalwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/nitraat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/omgekeerde-osmose/remineralisatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/nitraat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/outdoor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/koolstoffilter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/onderbouw`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/soorten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/koolstoffilter/chloor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/geur-smaak`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/koolstoffilter/leidingwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/uv-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/uv-filter/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/uv-filter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/uv-filter/toepassingen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/keramisch-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/sedimentfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/brita`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/brita-vs-bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/filter-vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontkalker`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/ultrafiltratie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/nanofiltration`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/quooker-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/quooker/filter-vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/quooker-cube`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/quooker-versus-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/quooker-prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/quooker-modellen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/quooker-onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/quooker-kalk`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/quooker-storing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/quooker-energieverbruik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/keramisch-filter/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keramisch-filter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keramisch-filter/soorten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/leidingwater/kwaliteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/kwaliteit-verbeteren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kraanwater/kwaliteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kraanwater/vs-gefilterd`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/sedimentfilter/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/sedimentfilter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/bacterien-testen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/ijzer-verwijderen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/mangaan-verwijderen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/nitraat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/zware-metalen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/uv-desinfectie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/omgekeerde-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/putwater/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/filteren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/drinken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/tuin`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/wc-doorspoelen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/wassen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/opslagtank`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/regenwater/pfas`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/pfas-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/lood-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/huurwoning`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/nieuwbouw`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/kantoor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwater/medicijnresten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/chloor-verwijderen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/chloor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/mineralen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/ijzer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/mangaan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/arsenicum`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/microplastics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/pesticiden`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwater/bacterien`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/baby`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/fluoride`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwater/hardheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/chlooramine`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/tds`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/zwaar-metalen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/gezondheidsvoordelen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kokend-water-kraan/vs-quooker`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/waterfilter/best-getest-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/drinkwater/kwaliteitsrapport`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/zout`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/aluminium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/osmose-water/vs-bronwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwater/nitraat-verlagen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/waterontharder/zoutloos`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/regeneratie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/hoe-lang`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater/bacterien`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kraanwater/hardheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/chloor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/verontreinigingen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/bacterien`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/hond-kat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/espresso`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-filter/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/thee`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/pfas-waterfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/pfas-waterfilter/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/pfas-waterfilter/testen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/pfas-waterfilter/normen-2026`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/pfas-waterfilter/gebieden-nederland`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/pfas-waterfilter/osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/pfas-waterfilter/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/pfas-waterfilter/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/pfas-waterfilter/huis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/pfas-waterfilter/pfas-soorten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Waterontkalker cluster
    { url: `${BASE}/waterontkalker/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontkalker/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/waterontkalker/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontkalker/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontkalker/vs-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontkalker/soorten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Heet-water-kraan cluster
    { url: `${BASE}/heet-water-kraan/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/heet-water-kraan/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/heet-water-kraan/installeren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/heet-water-kraan/prijs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/heet-water-kraan/filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Kalk-in cluster
    { url: `${BASE}/kalk-in`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kalk-in/filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kalk-in/cv-ketel`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kalk-in/douche`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kalk-in/wasmachine`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Waterfilter stoffen
    { url: `${BASE}/waterfilter/hormonen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/legionella`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/zink`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/koper`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/milieu`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/nitriet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/subsidie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Overig
    { url: `${BASE}/osmose-water/koffie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/hard-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/regeneratie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/hoe-lang`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater/bacterien`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kraanwater/hardheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/verontreinigingen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/bacterien`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/hond-kat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/espresso`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Brouwwater cluster
    { url: `${BASE}/brouwwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/brouwwater/osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/brouwwater/remineraliseren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/brouwwater/tds-profiel`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Vergelijkingspagina's
    { url: `${BASE}/waterfilter/vs-waterkoker`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/vs-gedistilleerd`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/vs-waterkraan-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Filterkan cluster
    { url: `${BASE}/filterkan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/brita`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/brita-vs-bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/filter-vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Situationele pagina's
    { url: `${BASE}/waterfilter/tiny-house`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/boot-jacht`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/woonboot`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/zomerhuis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/oudere-woning`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Waterkwaliteit cluster
    { url: `${BASE}/waterkwaliteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterkwaliteit/nederland`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterkwaliteit/europa`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterkwaliteit/test`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Ronde 4 — hoge prioriteit
    { url: `${BASE}/waterfilter/hormonen-medicijnen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/installatietijd`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-filter/vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kokend-water-kraan/huurwoning`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Filterkan cluster uitbreiding
    { url: `${BASE}/filterkan/werking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/brita`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filterkan/bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/brita-vs-bwt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filterkan/filter-vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Drinkwaterfontein cluster
    { url: `${BASE}/drinkwaterfontein`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaterfontein/kantoor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaterfontein/thuis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaterfontein/kopen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Reisfilter cluster
    { url: `${BASE}/reisfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/reisfilter/lifestraw`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/reisfilter/sawyer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Technische verdieping waterontharder
    { url: `${BASE}/waterontharder/installeren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/storingen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Technische verdieping osmose + kokend-water-kraan
    { url: `${BASE}/omgekeerde-osmose/membraan-vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/waterdruk`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/vs-ultrafiltratie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 5 — alkalisch water cluster
    { url: `${BASE}/alkalisch-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/alkalisch-water/gezondheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/alkalisch-water/ionisator`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/alkalisch-water/vs-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Bruisend water cluster
    { url: `${BASE}/bruisend-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/bruisend-water/kraan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/bruisend-water/sodastream`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/bruisend-water/co2`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Babywater cluster
    { url: `${BASE}/babywater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/babywater/welk-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/babywater/osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Osmose-water uitbreidingen
    { url: `${BASE}/osmose-water/vs-mineraalwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/vs-bronwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/gezondheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Situationeel
    { url: `${BASE}/waterfilter/caravan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Waterzuivering cluster
    { url: `${BASE}/waterzuivering`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterzuivering/grondwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterzuivering/oppervlaktewater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterzuivering/thuis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterzuivering/stappen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterbedrijven/vitens`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/evides`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/pwn`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/dunea`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/brabant-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/waternet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/wml`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/oasen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/wdl`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterbedrijven/waterbedrijf-groningen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // pH & mineralen
    { url: `${BASE}/kraanwater/ph`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/ijzer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/installeren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 6 — zakelijk cluster
    { url: `${BASE}/waterfilter/horeca`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/bedrijf`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaterfontein/horeca`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaterfontein/huren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaterfontein/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/zakelijk`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Osmose verdieping
    { url: `${BASE}/osmose-water/remineraliseren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-filter/zonder-tank`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/rendement`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Niche & vergelijkingen
    { url: `${BASE}/waterfilter/vijver`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/studentenkamer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/quooker`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/smaak`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Drinkwater verdieping
    { url: `${BASE}/leidingwater/nitraat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/mangaan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater/kwaliteit-verbeteren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/arseen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 7 — nieuwe clusters + verdieping
    { url: `${BASE}/waterfilter/aquarium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/gezondheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/huren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/kan-vs-kraan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/lood`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/medicijnresten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kraanwater/zomer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater/legionella-thuis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/chlooramine`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 8 — nieuwe clusters
    { url: `${BASE}/waterfilter/pesticiden`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/mineralen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/zout-gebruik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/installatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/hardheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kokend-water-kraan/energie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/kalium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 9
    { url: `${BASE}/waterfilter/waterverzachter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/ph`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/kosten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/sulfaat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater/tds`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 10
    { url: `${BASE}/waterfilter/nikkel`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/sport`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/capaciteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/regeneratie-tijd`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/hardheid-kaart`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/zeoliet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/koffie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Ronde 11
    { url: `${BASE}/waterfilter/chroom`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/druk`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/temperatuur`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/veiligheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/baby`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/geur`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 12
    { url: `${BASE}/waterfilter/radium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/afvalwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/zout-types`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/barium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/thee`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/aquarium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/fosfaat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 13
    { url: `${BASE}/waterfilter/strontium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/membraandruk`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/bypass`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/silica`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/schoonmaken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/mangan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kraanwater/ijzer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 14
    { url: `${BASE}/waterfilter/ammonium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/zout-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/elektromagnetisch`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/hardheid-meten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/kokend-water-kraan/stoom`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/wijn`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/sediment`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 15
    { url: `${BASE}/waterfilter/actief-kool`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/smaak`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/capaciteit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/uranium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/ijssteen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/chloride`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/levensduur`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Ronde 16
    { url: `${BASE}/waterfilter/bromaat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/diy`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterontharder/storingen-checklist`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/aluminium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/merken-vergelijking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/zwembad`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/uv-sterilisatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 17
    { url: `${BASE}/waterontharder/harsbed`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/natrium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/energie-verbruik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/fluor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 18
    { url: `${BASE}/omgekeerde-osmose/boosterpomp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/zout-verbruik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/installateur`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/koolzuur`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 19
    { url: `${BASE}/waterfilter/mangaanfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/capaciteit-liter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/twin-tank`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/pesticiden`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/garantie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/koffie-espresso`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/reisfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 20
    { url: `${BASE}/waterontharder/verhuurder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/kokend-water-kraan/kinderveiligheid`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/cryptosporidium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/totaaloplossing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/omgekeerde-osmose/inbouw`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/waterkwaliteitsrapport`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/fermenteren`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 21
    { url: `${BASE}/waterfilter/hardheidstest`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/omgekeerde-osmose/afvalwater-hergebruik`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterontharder/aquarium`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/leidingwater/zuurstof`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/kokend-water-kraan/prijs-per-liter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/zout-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/waterfilter/natriumhypochloriet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Drinkwaternormen hub
    { url: `${BASE}/drinkwaternormen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/drinkwaternormen/wie-controleert-drinkwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/drinkwaterbesluit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/eu-drinkwaterrichtlijn`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/drinkwaterbedrijven`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/waterfilter-certificering`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/kiwa-nsf-ansi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/pfas`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/lood`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/drinkwaternormen/kalk-hard-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaternormen/medicijnresten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaternormen/microplastics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaternormen/reverse-osmosis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Microplastics verdieping
    { url: `${BASE}/waterfilter/nanoplastics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/osmose-water/microplastics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 23: leidingwater contaminanten + drinkwaternormen chroom-6 + glyfosaat + baby
    { url: `${BASE}/leidingwater/pfas`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/chroom-6`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/lood`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/leidingwater/microplastics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/drinkwaternormen/chroom-6`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterfilter/glyfosaat`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/osmose-water/baby-flesvoeding`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Fase 2-3: 10-cluster architectuur
    { url: `${BASE}/keuzehulp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/keuzehulp/hard-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keuzehulp/pfas-lood`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keuzehulp/baby-gezin`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keuzehulp/huurwoning`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filtertechnieken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/filtertechnieken/actief-kool`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/filtertechnieken/ultrafiltratie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filtertechnieken/ionenwisseling`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/stoffen-in-drinkwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/keurmerken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/vergelijken/osmose-vs-filterkan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/vergelijken/waterfilter-vs-waterontharder`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-waterfilter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/beste-waterfilter/appartement`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-waterfilter/huurwoning`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-waterfilter/ouder-huis`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-waterfilter/koffie-thee`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterhardheid/per-provincie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/waterhardheid/effect-op-koffie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterhardheid/behandelingsadvies`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/onderhoud/osmose-filter-vervangen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/onderhoud/filterkan-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/onderhoud/storingen-oplossen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/zakelijk`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/zakelijk/horeca`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/kantoor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Ronde 23 — nieuwe cluster sub-pagina's
    { url: `${BASE}/vergelijken/kraanwater-vs-flessenwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/vergelijken/osmose-vs-bronwater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/vergelijken/kokend-water-kraan-merken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/vergelijken/omgekeerde-osmose-vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/vergelijken/waterontharder-vergelijken`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-waterfilter/woonboot`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/beste-waterfilter/hard-water-gebied`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/onderhoud/waterontharder-zout`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/onderhoud/kokend-water-kraan-onderhoud`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/onderhoud/koolstoffilter-levensduur`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/industrie-proceswater`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/appartementen-vve`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/scholen-kinderopvang`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/sportschool-wellness`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/waterkoeler-vs-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/legionella-beheersplan`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/zakelijk/waterkwaliteitsanalyse`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Stoffen-in-drinkwater sub-pagina's
    { url: `${BASE}/stoffen-in-drinkwater/zware-metalen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/stoffen-in-drinkwater/pesticiden`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/stoffen-in-drinkwater/pfas-overzicht`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/stoffen-in-drinkwater/microbiologisch`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/stoffen-in-drinkwater/kalk-mineralen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/stoffen-in-drinkwater/nitraat-nitriet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/stoffen-in-drinkwater/chloor-bijproducten`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/stoffen-in-drinkwater/hormonen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/stoffen-in-drinkwater/radioactieve-stoffen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Filtertechnieken sub-pagina's
    { url: `${BASE}/filtertechnieken/keramisch`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filtertechnieken/nanofiltration`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filtertechnieken/elektrolyse-cdi`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filtertechnieken/vergelijking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Keuzehulp sub-pagina's
    { url: `${BASE}/keuzehulp/geur-smaak`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keuzehulp/budget`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keuzehulp/buitenland-reizen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keuzehulp/installatie-type`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Beste-waterfilter sub-pagina's
    { url: `${BASE}/beste-waterfilter/studentenkamer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/beste-waterfilter/budget-onder-100`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/beste-waterfilter/all-in-one`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/beste-waterfilter/ecologisch`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Keurmerken sub-pagina's
    { url: `${BASE}/keurmerken/nsf-ansi-58`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keurmerken/nsf-ansi-42-53`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keurmerken/nsf-ansi-401`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keurmerken/kiwa-113`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/keurmerken/acs`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keurmerken/ce-markering`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keurmerken/wras`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/keurmerken/verificatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Onderhoud sub-pagina's
    { url: `${BASE}/onderhoud/filterkan-filter`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/onderhoud/storingen-oplossen`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Osmose-water hub (was missing, linked from 33 pages)
    { url: `${BASE}/osmose-water`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    // Aanvulling sitemap-volledigheid (check-sitemap)
    { url: `${BASE}/filtertechnieken/omgekeerde-osmose`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/filtertechnieken/uv-sterilisatie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/waterfilter/gezin`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/waterfilter/wijn-bier`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
  ];

  // One git lookup per gemeente template (shared across all 350 gemeenten).
  const gemeenteDates: Record<string, Date> = Object.fromEntries(
    ['waterhardheid', 'drinkwater', 'kalk-in', 'waterontharder', 'waterfilter',
     'osmose-filter', 'kraanwater', 'leidingwater', 'kokend-water-kraan', 'waterontkalker']
      .map(seg => [seg, gemeenteTemplateDate(seg)]),
  );

  const gemeentePages: MetadataRoute.Sitemap = gemeenten.flatMap(g => [
    { url: `${BASE}/waterhardheid/${g.slug}`, lastModified: gemeenteDates['waterhardheid'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/drinkwater/${g.slug}`, lastModified: gemeenteDates['drinkwater'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/kalk-in/${g.slug}`, lastModified: gemeenteDates['kalk-in'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/waterontharder/${g.slug}`, lastModified: gemeenteDates['waterontharder'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/waterfilter/${g.slug}`, lastModified: gemeenteDates['waterfilter'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/osmose-filter/${g.slug}`, lastModified: gemeenteDates['osmose-filter'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/kraanwater/${g.slug}`, lastModified: gemeenteDates['kraanwater'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/leidingwater/${g.slug}`, lastModified: gemeenteDates['leidingwater'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/kokend-water-kraan/${g.slug}`, lastModified: gemeenteDates['kokend-water-kraan'], changeFrequency: 'yearly' as const, priority: 0.5 },
    { url: `${BASE}/waterontkalker/${g.slug}`, lastModified: gemeenteDates['waterontkalker'], changeFrequency: 'yearly' as const, priority: 0.5 },
  ]);

  const contentDir = path.join(process.cwd(), 'content/kennisbank');
  const kennisbankPages: MetadataRoute.Sitemap = getKennisbankSlugs().map(slug => ({
    url: `${BASE}/kennisbank/${slug}`,
    lastModified: pickLastModified({
      frontmatterDate: mdxFrontmatterDate(path.join(contentDir, `${slug}.mdx`)),
      buildDate: BUILD_DATE,
    }),
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Override the placeholder dates on the static entries with the source file's
  // git-commit date (fallback: build date), keyed by the literal URL path.
  const staticPagesWithDates: MetadataRoute.Sitemap = staticPages.map(p => ({
    ...p,
    lastModified: routeLastModified(String(p.url).slice(BASE.length) || '/', BUILD_DATE),
  }));

  return [...staticPagesWithDates, ...gemeentePages, ...kennisbankPages];
}
